web/netlify.toml

[#27] : 프로젝트설정
<br />
- 버그 수정
<br/>
[#27] 프로젝트설정
- 배포환경 라우팅을 위한 netlify.toml 설정
<br />

[#27]/fix 프로젝트설정

---

web/src/App.tsx
web/src/assets/styles/styled.d.ts
web/src/assets/styles/theme.ts
web/src/components/footer/index.tsx
web/src/components/header/Folder.tsx
web/src/components/header/Info.tsx
web/src/components/header/Logo.tsx
web/src/components/header/SearchBar.tsx
web/src/components/header/index.tsx
web/src/pages/MainPage.tsx

[#45] : 페이지 레이아웃 리팩토링
<br />
- 리펙토링
<br/>
[#45] 페이지 레이아웃 리팩토링
- 헤더 레이아웃 리팩토링
- 푸터 레이아웃 리팩토링
- 메인 레이아웃 리팩토링
<br />

[#45]/feat 페이지 레이아웃 리팩토링

---

web/src/assets/styles/styled.d.ts
web/src/assets/styles/theme.ts
web/src/components/common/SimpleButton.tsx
web/src/components/mypage/AccountSetting.tsx
web/src/components/mypage/Profile.tsx

[#46] : 버튼 컴포넌트 리팩토링
<br />
- 리펙토링
<br/>
[#46] 버튼 컴포넌트 리팩토링
<br />

[#46]/refactor 버튼 컴포넌트 리팩토링

---

web/src/components/bookmark/FilterBox.tsx
web/src/components/common/ToggleIconButton.tsx
web/src/components/mypage/Configuration.tsx

[#48] : 토글 컴포넌트 리팩토링
<br />
- 리펙토링
<br/>
> 작업한 목록
- 토글 컴포넌트 리팩토링
<br />

[#48]/refactor 토글 컴포넌트 리팩토링

---

web/src/components/common/SimpleInput.tsx

[#49] : 인풋 컴포넌트 리팩토링
<br />
- 리펙토링
<br/>
> 작업한 목록
- 인풋 컴포넌트 리팩토링
<br />

[#49]/refactor 인풋 컴포넌트 리팩토링

---

web/src/components/common/ChipButton.tsx
web/src/components/mypage/Configuration.tsx

[#50] : 칩 컴포넌트 리팩토링
<br />
- 리펙토링
<br/>
> 작업한 목록
- 칩 컴포넌트 리팩토링
<br />

[#50]/refactor 칩 컴포넌트 리팩토링

---

web/package-lock.json
web/package.json
web/src/App.tsx

[#14] : 웹 환경설정
<br />
- 리펙토링
<br/>
> 작업한 목록
- react-router-dom v5 -> v6 마이그레이션
<br />

[#14]/fix 웹 환경설정

---

web/package-lock.json
web/package.json
web/src/App.tsx
web/src/pages/ErrorPage.tsx

[#58] : Error Boundary 설정
<br />
- 신규 기능 추가
<br/>
> 작업한 목록
- [#58] Error Boundary 설정
- react-error-boundary
<br />
기본 Error Boundary 세팅으로는 이벤트핸들링, 비동기, SSR, Error Boundary 내부의 
에러를 잡아내지 못함 
추후 React Query, Axios 에서 error handling 사용하게 될 시 Error boundary 사용성 검토 필요

[#58]/feat Error Boundary 설정

---

web/.eslintrc.js
web/src/App.tsx
web/src/routes/Routing.tsx
web/src/routes/path.ts

[#56] : Path Routing
<br />
- 신규 기능 추가
- 리펙토링
<br/>
> 작업한 목록
- [#56] Path Routing
- Enum Path 정의
- App , Routing 분리
<br />

[#56]/feat Path Routing

---

web/src/assets/icons/Icons_Search_24.svg
web/src/assets/icons/index.ts
web/src/components/header/SearchBar.tsx

[#32] : 서치바 UI
<br />
- 신규 기능 추가
- 리펙토링
<br/>
[#32] : 서치바 UI
<br />
- 상위 엘리먼트에서 opacity를 주면 하위 엘리먼트에 영향을 주는데요.
이부분을 상위 엘리먼트만 받을 수 있게 하는 방법이 있을까요? 지금은 rgba로 주었습니다!

[#32]/feat 서치바 UI

---

web/src/components/footer/index.tsx
web/yarn.lock

[#41] : 푸터 기능
<br />
- 리펙토링
<br/>
> 작업한 목록
- 서비스 이용약관, 개인정보 처리방침 url 수정
<br />

[#41]/fix 푸터 기능

---

web/src/api/bookmarkAPI.ts
web/src/components/bookmark/BookmarkItem.tsx
web/src/components/bookmark/BookmarkList.tsx
web/src/components/bookmark/data/bookmarkMock.json
web/src/hooks/bookmark/useBookmarksEffect.ts
web/src/pages/MainPage.tsx
web/src/recoil/atoms/bookmarkState.ts
web/src/routes/Routing.tsx
web/src/routes/path.ts
web/yarn.lock

[#43] : 북마크 카드 상태관리
<br />
- 신규 기능 추가
<br/>
> 작업한 목록
- 북마크 카드 상태관리
<br />

[#43]/feat 북마크 카드 상태관리

---

web/src/api/bookmarkAPI.ts
web/src/api/http.ts
web/src/components/bookmark/BookmarkItem.tsx
web/src/hooks/bookmark/useBookmarkQueries.ts
web/src/models/bookmark.d.ts

[#68]: 북마크 API using mutation
<br />
- 신규 기능 추가
- 리펙토링
<br/>
> 작업한 목록
[#68]: 북마크 API using mutation
<br />
- patch, delete axios 추가
- update, delete, move bookmark api 추가
- mutation hook 구현

[#68]/feat 북마크 API using mutation

---

web/src/api/bookmarkAPI.ts
web/src/components/bookmark/index.tsx
web/src/hooks/bookmark/useBookmarkQueries.ts

[#69]: Search API 추가 
<br />
- 신규 기능 추가
<br/>
> 작업한 목록
[#69]: Search API 추가 
<br />
- Search 를 통한 조회도 타 API와 동일한 구조로 사용하게 작성했습니다.

[#69]/feat Search API

---

web/src/hooks/auth/useGoogleLogin.ts
web/src/routes/Routing.tsx
web/src/routes/path.ts

[#72] : Not Found 페이지 라우트 수정
<br />
- 버그 수정
- 리펙토링
<br/>
> 작업한 목록
- Not Found 페이지 라우트 수정
<br />

[#72]/fix Not Found 페이지 라우트 수정

---

web/src/api/authAPI.ts
web/src/api/bookmarkAPI.ts
web/src/api/remindAPI.ts
web/src/components/mypage/Configuration.tsx
web/src/hooks/auth/useGoogleLogin.ts
web/src/models/auth.d.ts
web/src/models/remind.d.ts
web/src/recoil/atoms/initializer.ts
web/src/recoil/atoms/userState.ts
web/src/utils/auth.ts
web/src/utils/const.ts

[#70]: userInfo 변경, remind toggle, cycle api
<br />
- 신규 기능 추가
<br/>
> 작업한 목록
[#70]: userInfo 변경, remind toggle, cycle api
<br />

[#70]/feat userInfo 변경, remind toggle, cycle api

---

web/src/components/bookmark/index.tsx
web/src/components/subFolders/index.tsx
web/src/pages/MainPage.tsx

[#30]: SubFolders 위치 변경
<br />
- 버그 수정
<br/>
> 작업한 목록
- SubFolders 위치 변경
<br />

[#30]/fix SubFolders 위치 변경

---

web/src/api/bookmarkAPI.ts
web/src/components/bookmark/index.tsx
web/src/hooks/bookmark/useBookmarkQueries.ts
web/src/pages/MainPage.tsx

[#75] : 크롬익스텐션
<br />
- 신규 기능 추가
- 버그 수정
<br/>
> 작업한 목록
- 각 라우팅 별로 북마크 불러오기
<br />

[#75]/feat 각 라우팅별로 북마크 불러오기

---

web/src/hooks/bookmark/useBookmarkQueries.ts
web/src/utils/const.ts

[#80]: fix queryKeyOptions
<br />
- 버그 수정
<br/>
> 작업한 목록
[#80]: fix queryKeyOptions
<br />
- 특이 사항 1
- 특이 사항 2

[#80]/fix queryKeyOptions

---

web/src/components/bookmark/BookmarkEditModal.tsx
web/src/components/bookmark/BookmarkItem.tsx
web/src/components/bookmark/BookmarkList.tsx
web/src/components/bookmark/BookmarkMenu.tsx
web/src/components/bookmark/FilterBox.tsx
web/src/components/bookmark/SelectBox.tsx
web/src/components/bookmark/index.tsx
web/src/components/common/FolderListInModal.tsx
web/src/components/common/SmallModal.tsx
web/src/components/sidebar/FolderList.tsx
web/src/components/sidebar/FolderMoveModal.tsx
web/src/hooks/bookmark/useHandleBookmark.ts
web/src/models/bookmark.d.ts

[#76] : 북마크 메뉴 기능(편집, 삭제)
<br />
- 신규 기능 추가
<br/>
> 작업한 목록
- 북마크 메뉴 기능(편집, 삭제)
<br />
- 특이 사항 1
- 특이 사항 2

[#76]/feat 북마크 메뉴 기능(편집, 삭제)

---

web/src/components/header/Logo.tsx
web/src/components/header/index.tsx

[#79] : Header 조건 추가
<br />
- 신규 기능 추가
<br/>
> 작업한 목록
- Header 조건 추가
<br />
- 특이 사항 1
- 특이 사항 2

[#79]/fix Header 조건 추가

---

web/src/components/mypage/Configuration.tsx
web/src/utils/remind.ts

[#81]: fix set localstorage remind use info
<br />
- 신규 기능 추가
<br/>
> 작업한 목록
[#81]: fix set localstorage remind use info
<br />

[#81]/fix set localstorage remind use info

---

web/src/components/sidebar/TestModal.tsx
web/src/components/sidebar/index.tsx

[#1] : 크롬익스텐션
<br />
-  북마크 추가 테스트 버튼
<br/>
> 작업한 목록
- 북마크 추가 테스트 버튼
<br />

[#82]/feat 북마크 추가 테스트 버튼

---

web/src/components/sidebar/index.tsx
web/src/components/subFolders/SubFolderListItem.tsx

[#82] :  scroll 삭제
<br />
- 버그 수정
<br/>
> 작업한 목록
-  scroll 삭제
<br />

[#82]/fix scroll 삭제

---

web/src/components/header/Info.tsx
web/src/components/mypage/Profile.tsx
web/src/components/mypage/ProfileEditForm.tsx
web/src/hooks/auth/useGoogleLogin.ts
web/src/models/auth.d.ts
web/src/recoil/atoms/initializer.ts
web/src/recoil/atoms/userState.ts

[#82] :  image type 수정
<br />
- 버그 수정
<br/>
> 작업한 목록
-  image type 수정
<br />
- 특이 사항 1
- 특이 사항 2

[#82]/feat image type 수정

---

web/src/components/bookmark/BookmarkItem.tsx
web/src/components/tutorial/QuestionButton.tsx

[#82] : 북마크 색상변경, url 등록
<br />
- 버그 수정
<br/>
> 작업한 목록
- 북마크 색상변경, url 등록
<br />

[#82]/fix 북마크 색상변경, url 등록

---

web/src/api/bookmarkAPI.ts
web/src/api/remindAPI.ts
web/src/components/reminder/RemindList.tsx
web/src/components/reminder/RemindListItem.tsx
web/src/hooks/reminder/useRemindQueries.ts
web/src/hooks/reminder/useReminderHandleEffect.ts
web/src/models/remind.d.ts
web/src/utils/const.ts

[#83]: getList remind, delte query & API
<br />
- 신규 기능 추가
<br/>
> 작업한 목록
[#83]: getList remind, delte query & API
<br />
서버 API 완료시 반영 테스트 필요합니다.

[#83]/feat getList remind, delete query & API

---

web/src/components/auth/AuthTemplate.tsx
web/src/hooks/auth/useGoogleLogin.ts
web/src/pages/LoginPage.tsx

[#84] : 2차 범위 삭제
<br />
- 버그 수정
<br/>
> 작업한 목록
- 2차 범위 삭제
<br />
- 특이 사항 1
- 특이 사항 2

[#84]/fix 2차 범위 삭제

---

web/src/api/bookmarkAPI.ts
web/src/components/bookmark/BookmarkItem.tsx
web/src/components/bookmark/index.tsx
web/src/components/sidebar/FolderList.tsx
web/src/components/sidebar/TestModal.tsx

[#84] : 북마크 클릭카운트 구현
<br />
- 신규 기능 추가
<br/>
> 작업한 목록
- 북마크 클릭카운트 구현
<br />
- 특이 사항 1
- 특이 사항 2

[#84]/feat 북마크 클릭카운트 구현

---

web/src/components/common/Toasts.tsx
web/src/components/mypage/ProfileEditForm.tsx

[#85]/fix 마이페이지 수정 모달x
<br />
- 버그 수정
- 리펙토링
<br/>
> 작업한 목록
- 마이페이지 수정 모달x
<br />
- 특이 사항 1
- 특이 사항 2

[#85]/fix 마이페이지 수정 모달x

---

web/src/components/bookmark/BookmarkItem.tsx
web/src/components/bookmark/BookmarkMenu.tsx
web/src/components/pagePath/GlobalPath.tsx
web/src/components/sidebar/index.tsx
web/src/hooks/folder/useFoldersHandle.ts
web/src/utils/atlaskitTreeFinder.ts

[#85] : 토스트 메뉴, 오타, 북마크 오류 해결
<br />
- 신규 기능 추가
- 버그 수정
<br/>
> 작업한 목록
- 리마인드를 on해주세요 토스트 메세지 나오는거 - 서정님
- 휴지통에서 북마크 기능 비활성화 되지 않음 - 지환님
- '모든 도토리' 소제목 텍스트 오류 - 예람님
- 생성 가능한 폴더 개수 초과 시 토스트 메세지 노출 - 예람님
- 북마크 이동 폴더 선택시, 첫 시도는 실패함 - 서정님
<br />

[#85]/fix 토스트 메뉴, 오타, 북마크 오류 해결

---

web/src/components/bookmark/index.tsx
web/src/components/sidebar/FolderList.tsx

[#85] : 휴지통에 리마인드 도토리/필터링 부분 삭제
<br />
- 버그 수정
<br/>
> 작업한 목록
- 휴지통에 리마인드 도토리/필터링 부분 삭제
<br />

[#85]/fix 휴지통에 리마인드 도토리/필터링 부분 삭제

---

web/src/components/mypage/ProfileEditForm.tsx
web/src/components/mypage/ProfileNicknameForm.tsx
web/src/components/sidebar/FolderList.tsx
web/src/pages/MyPage.tsx
web/src/recoil/atoms/toastState.ts

[#85] : 휴지통에서 새로고침시 모든도토리로 이동 현상
<br />
- 버그 수정
<br/>
> 작업한 목록
- 휴지통에서 새로고침시 모든도토리로 이동 현상
<br />

[#85]/fix 휴지통에서 새로고침시 모든도토리로 이동 현상

---

web/src/components/bookmark/BookmarkItem.tsx

[#85] : 복원한 북마크의 폴더 영역 변경
<br />
- 신규 기능 추가
- 버그 수정
<br/>
> 작업한 목록
- 복원한 북마크의 폴더 영역 변경
<br />
- 특이 사항 1
- 특이 사항 2

[#85]/fix 복원한 북마크의 폴더 영역 변경

---

web/src/api/folderAPI.ts
web/src/hooks/folder/useFoldersHandle.ts

[#85] : 폴더, 보관함 드래그앤 드롭 이동 관련
<br />
- 버그 수정
<br/>
> 작업한 목록
- 폴더, 보관함 드래그앤 드롭 이동 관련
<br />
- 특이 사항 1
- 특이 사항 2

[#85]/fix 폴더, 보관함 드래그앤 드롭 이동 관련

---

web/src/components/sidebar/FolderMoveModal.tsx

[#85] : 이동 모달 버튼 색상 수정
<br />
- 버그 수정
<br/>
> 작업한 목록
- 이동 모달 버튼 색상 수정
<br />

[#85]/fix 이동 모달 버튼 색상 수정

---

web/src/components/common/SimpleInput.tsx

[#85] : 폴더 이름 변경시 입력 커서 이동
<br />
- 신규 기능 추가
- 버그 수정
<br/>
> 작업한 목록
- 폴더 이름 변경시 입력 커서 이동
<br />
- 특이 사항 1
- 특이 사항 2

[#85]/fix 폴더 이름 변경시 입력 커서 이동

---

web/src/components/auth/AuthTemplate.tsx
web/src/components/sidebar/TestModal.tsx

[#85] : 크롬익스텐션
<br />
- 버그 수정
<br/>
> 작업한 목록
- api key 수정
<br />
- 특이 사항 1
- 특이 사항 2

[#85]/fix api key 수정

---

web/package-lock.json
web/package.json
web/public/firebase-messaging-sw.js
web/src/App.tsx
web/src/hooks/auth/useGoogleLogin.ts
web/src/models/auth.d.ts
web/src/utils/config.ts
web/src/utils/firebase.ts

[#86]: firebase 연동
<br />
- 신규 기능 추가
<br/>
> 작업한 목록
- [#86]: firebase 연동
<br />
- 테스트입니다

[#86]/feat firebase 연동

---

web/package.json
web/src/assets/icons/Trash_Ballon.svg
web/src/assets/icons/index.ts
web/src/components/bookmark/BookmarkEditModal.tsx
web/src/components/bookmark/FilterBox.tsx
web/src/components/common/ModalTemplate.tsx
web/src/components/reminder/RemindListItem.tsx
web/src/components/sidebar/TrashBox.tsx
web/src/hooks/folder/useFoldersHandle.ts
web/src/hooks/folder/useFoldersQueries.ts
web/yarn.lock

[#85] : qa 수정 사항 반영
<br />
- 버그 수정
- 리펙토링
<br/>
> 작업한 목록
- 북마크 편집 모달창 크기 수정 + 100자 되면 색 변경되게 수정
- 리마인드 태두리 여백 없애기
- 휴지통 마우스 오버하면 설명 풍선 나오게 설정
- 리마인드 설명 풍선 텍스트 검정으로 변경
- 폴더 이름 변경 미 반영 수정
- 이동 모달창 실시간으로 반영되지 않은 거 수정
- 상위 보관함 삭제 시 하위 폴더 내의 북마크 삭제 실시간 반영(프론트 쪽 완료)
<br />
- 특이 사항 1
- 특이 사항 2

[#85]/fix qa 수정 사항 반영

---

web/public/firebase-messaging-sw.mjs

[#86]/fix firebase service worker
<br />
- 버그 수정
<br/>
> 작업한 목록
[#86]/fix firebase service worker
<br />

[#86]/fix firebase service worker

---

web/public/firebase-messaging-sw.mjs

[#86]/fix firebase service worker config option
<br />
- 버그 수정
<br/>
> 작업한 목록
[#86]/fix firebase service worker config option
<br />

[#86]/fix firebase service worker config option

---

web/src/hooks/auth/useGoogleLogin.ts

[#86]/fix not use getToken just for a while
<br />
- 버그 수정
<br/>
> 작업한 목록
[#86]/fix not use getToken just for a while
<br />

[#86]/fix not use getToken just for a while

---

web/public/firebase-messaging-sw.js
web/src/hooks/auth/useGoogleLogin.ts

[#88]: set sw of firebase
<br />
- 버그 수정
<br/>
> 작업한 목록
- set sw of firebase
<br />

[#88]/fix set sw of firebase

---

web/src/components/reminder/RemindAlertMessage.tsx
web/src/components/reminder/RemindList.tsx
web/src/components/reminder/RemindListItem.tsx
web/src/hooks/bookmark/useHandleBookmark.ts
web/yarn.lock

[#85] : 리마인드 qa
<br />
- 신규 기능 추가
<br/>
> 작업한 목록
- 리마인드 설정 off 시에 메세지 보여주기
- 북마크 리마인드 설정시 리마인드 리스트에 실시간 반영
- 리마인드 아이템 삭제시 북마크 실시간 반영
<br />

[#85]/feat 리마인드 qa

---

web/src/api/folderAPI.ts
web/src/components/bookmark/BookmarkItem.tsx
web/src/components/bookmark/BookmarkList.tsx
web/src/components/bookmark/BookmarkMenu.tsx
web/src/components/bookmark/index.tsx
web/src/components/common/FolderListInModal.tsx
web/src/components/sidebar/FolderList.tsx
web/src/components/sidebar/FolderMoveModal.tsx
web/src/hooks/folder/useFoldersHandle.ts

[#85] : qa 수정 사항
<br />
- 신규 기능 추가
<br/>
> 작업한 목록
- 폴더 모달로 이동 
- 북마크 이동시에 path 안나오던거 수정
<br />
- 특이 사항 1
- 특이 사항 2

[#85]/feat qa 수정 사항

---

landing/src/components/Section1.tsx
web/src/components/auth/AuthTemplate.tsx
web/src/components/auth/AuthTitle.tsx
web/src/components/common/Toasts.tsx
web/src/components/reminder/RemindList.tsx

[#85] : 1월8일 qa 관련
<br />
- 버그 수정
<br/>
> 작업한 목록
- 랜딩페이지 오타 수정 
- 로그인 회원가입 구글만 보이도록 설정
- 리마인드 메세지 보이는 상황 수정
<br />
- 특이 사항 1
- 특이 사항 2

[#85]/fix 1월8일 qa 관련

---

web/src/components/mypage/ProfileEditButtonGroup.tsx
web/src/components/mypage/ProfileEditForm.tsx
web/src/components/mypage/ProfileNicknameForm.tsx

[#85] : 마이페이지 닉네임 변경 오류
<br />
- 신규 기능 추가
- 버그 수정
<br/>
> 작업한 목록
- 마이페이지 닉네임 변경 오류
<br />
- 특이 사항 1
- 특이 사항 2

[#85]/fix 마이페이지 닉네임 변경 오류

---

web/src/api/remindAPI.ts
web/src/components/header/Info.tsx
web/src/components/header/RemindHistory.tsx
web/src/hooks/reminder/useRemindQueries.ts
web/src/models/remind.d.ts
web/src/recoil/atoms/bellState.ts
web/src/utils/const.ts
web/src/utils/time.ts

[#35]: 리마인드 알림 기능
<br />
- 신규 기능 추가
- 리펙토링
<br/>
> 작업한 목록
[#35]: 리마인드 알림 기능
<br />
- 기존 임시로 사용하던 bellstate 삭제 했습니다.

[#35]/feat 리마인드 알림 기능

---

web/src/api/http.ts

[#89]: refresh token error
<br />
- 버그 수정
<br/>
> 작업한 목록
- refresh token error handling 추가
<br />
- refresh token error 일 경우, 로그아웃

[#89]/fix refresh token error

---

web/src/components/header/Info.tsx
web/src/components/header/RemindHistory.tsx
web/src/hooks/reminder/useRemindQueries.ts

[#35]: apply optimistic update in checking of remindAlarm
<br />
- 신규 기능 추가
- 리펙토링
<br/>
> 작업한 목록
[#35]: apply optimistic update in checking of remindAlarm
- 읽음 확인 처리를 위해 optimistic update 적용
<br />

[#35]/feat apply optimistic update in checking of remindAlarm

---

web/package-lock.json
web/package.json
web/src/index.tsx

[#101]: add react web vitals for analytics
<br />
- 신규 기능 추가
<br/>

[#101]/feat add react web vitals for analytics

---

web/src/index.tsx

[#101]: add initial ReactGA
<br />
- 신규 기능 추가
<br/>
> 작업한 목록
[#101]: add initial ReactGA

[#101]/fix add initial ReactGA

---

web/public/index.html

[#101]: add gtag
<br />
- 신규 기능 추가
<br/>
> 작업한 목록
[#101]: add gtag

[#101]/fix add gtag
